-- Идемпотентное наполнение каталога; пользовательские данные не изменяются.
INSERT INTO genres(id,name) VALUES (1,'Фантастика'),(2,'Драма'),(3,'Комедия'),(4,'Приключения'),(5,'Триллер'),(6,'Мелодрама') ON CONFLICT DO NOTHING;
INSERT INTO movies(id,title,original_title,year,director,duration,description,poster,accent) VALUES(1,'Интерстеллар','Interstellar',2014,'Кристофер Нолан',169,'Когда Земля перестаёт быть домом, группа исследователей отправляется за пределы Солнечной системы. История о расстояниях, которые измеряются не только световыми годами.','/posters/1.svg','#203943') ON CONFLICT DO NOTHING;
INSERT INTO movie_genres(movie_id,genre_id) VALUES (1,1),(1,2) ON CONFLICT DO NOTHING;
INSERT INTO quotes(id,movie_id,text) VALUES(1,1,'Любовь — это то, что мы способны воспринимать.') ON CONFLICT DO NOTHING;
INSERT INTO movies(id,title,original_title,year,director,duration,description,poster,accent) VALUES(2,'Отель «Гранд Будапешт»','The Grand Budapest Hotel',2014,'Уэс Андерсон',100,'Консьерж старинного отеля и его молодой помощник оказываются в центре истории с наследством, картиной и погоней. За безупречной симметрией скрывается память об исчезающем мире.','/posters/2.svg','#bf817b') ON CONFLICT DO NOTHING;
INSERT INTO movie_genres(movie_id,genre_id) VALUES (2,3),(2,4) ON CONFLICT DO NOTHING;
INSERT INTO quotes(id,movie_id,text) VALUES(2,2,'Всё ещё остались слабые проблески цивилизации.') ON CONFLICT DO NOTHING;
INSERT INTO movies(id,title,original_title,year,director,duration,description,poster,accent) VALUES(3,'Начало','Inception',2010,'Кристофер Нолан',148,'Специалист по проникновению в чужие сны получает обратную задачу: не украсть мысль, а заронить её. Чем глубже сон, тем сложнее отличить возвращение от очередного уровня.','/posters/3.svg','#24434a') ON CONFLICT DO NOTHING;
INSERT INTO movie_genres(movie_id,genre_id) VALUES (3,1),(3,5) ON CONFLICT DO NOTHING;
INSERT INTO quotes(id,movie_id,text) VALUES(3,3,'Ты ждёшь поезд.') ON CONFLICT DO NOTHING;
INSERT INTO movies(id,title,original_title,year,director,duration,description,poster,accent) VALUES(4,'Амели','Le Fabuleux Destin d’Amélie Poulain',2001,'Жан-Пьер Жёне',122,'Девушка с Монмартра незаметно меняет жизнь окружающих маленькими поступками. Помогая другим решиться на счастье, ей предстоит сделать собственный шаг.','/posters/4.svg','#385344') ON CONFLICT DO NOTHING;
INSERT INTO movie_genres(movie_id,genre_id) VALUES (4,3),(4,6) ON CONFLICT DO NOTHING;
INSERT INTO quotes(id,movie_id,text) VALUES(4,4,'Без тебя сегодняшние чувства — лишь обрывки вчерашних.') ON CONFLICT DO NOTHING;
INSERT INTO movies(id,title,original_title,year,director,duration,description,poster,accent) VALUES(5,'Шоу Трумана','The Truman Show',1998,'Питер Уир',103,'Привычная жизнь Трумана начинает давать сбои. Случайные детали заставляют его задуматься, кто определяет границы его мира и можно ли выйти за них.','/posters/5.svg','#6e9aab') ON CONFLICT DO NOTHING;
INSERT INTO movie_genres(movie_id,genre_id) VALUES (5,2),(5,3) ON CONFLICT DO NOTHING;
INSERT INTO quotes(id,movie_id,text) VALUES(5,5,'Доброе утро!') ON CONFLICT DO NOTHING;
INSERT INTO movies(id,title,original_title,year,director,duration,description,poster,accent) VALUES(6,'Общество мёртвых поэтов','Dead Poets Society',1989,'Питер Уир',128,'Новый преподаватель литературы предлагает ученикам строгой школы услышать собственный голос. Поэзия становится для них способом иначе посмотреть на будущее.','/posters/6.svg','#5b4335') ON CONFLICT DO NOTHING;
INSERT INTO movie_genres(movie_id,genre_id) VALUES (6,2) ON CONFLICT DO NOTHING;
INSERT INTO quotes(id,movie_id,text) VALUES(6,6,'Лови момент') ON CONFLICT DO NOTHING;
INSERT INTO movies(id,title,original_title,year,director,duration,description,poster,accent) VALUES(7,'Ла-Ла Ленд','La La Land',2016,'Дэмьен Шазелл',128,'Начинающая актриса и джазовый музыкант встречаются в Лос-Анджелесе. Их сближают мечты, но путь к ним требует решений, для которых нет идеального момента.','/posters/7.svg','#42446b') ON CONFLICT DO NOTHING;
INSERT INTO movie_genres(movie_id,genre_id) VALUES (7,6),(7,2) ON CONFLICT DO NOTHING;
INSERT INTO quotes(id,movie_id,text) VALUES(7,7,'За тех, кто мечтает.') ON CONFLICT DO NOTHING;
INSERT INTO movies(id,title,original_title,year,director,duration,description,poster,accent) VALUES(8,'Дюна','Dune',2021,'Дени Вильнёв',155,'Наследник знатного дома прибывает на пустынную планету, от которой зависит целая империя. Пески Арракиса меняют представления о власти, долге и предназначении.','/posters/8.svg','#b47945') ON CONFLICT DO NOTHING;
INSERT INTO movie_genres(movie_id,genre_id) VALUES (8,1),(8,4) ON CONFLICT DO NOTHING;
INSERT INTO quotes(id,movie_id,text) VALUES(8,8,'Страх убивает разум.') ON CONFLICT DO NOTHING;
INSERT INTO movies(id,title,original_title,year,director,duration,description,poster,accent) VALUES(9,'Унесённые призраками','Spirited Away',2001,'Хаяо Миядзаки',125,'Во время переезда девочка попадает в мир духов и вынуждена искать способ спасти родителей. Чтобы вернуться домой, ей важно не забыть собственное имя.','/posters/9.svg','#517f79') ON CONFLICT DO NOTHING;
INSERT INTO movie_genres(movie_id,genre_id) VALUES (9,4) ON CONFLICT DO NOTHING;
INSERT INTO quotes(id,movie_id,text) VALUES(9,9,'Не забывай своё имя.') ON CONFLICT DO NOTHING;
INSERT INTO movies(id,title,original_title,year,director,duration,description,poster,accent) VALUES(10,'Прибытие','Arrival',2016,'Дени Вильнёв',116,'Лингвист пытается понять язык существ, прибывших на Землю. Каждый найденный смысл меняет не только ход переговоров, но и её восприятие времени.','/posters/10.svg','#73796c') ON CONFLICT DO NOTHING;
INSERT INTO movie_genres(movie_id,genre_id) VALUES (10,1),(10,2) ON CONFLICT DO NOTHING;
INSERT INTO quotes(id,movie_id,text) VALUES(10,10,'Язык — основа цивилизации.') ON CONFLICT DO NOTHING;
INSERT INTO movies(id,title,original_title,year,director,duration,description,poster,accent) VALUES(11,'Достать ножи','Knives Out',2019,'Райан Джонсон',130,'Смерть известного писателя собирает семью, у каждого члена которой есть своя версия событий. Частный детектив распутывает историю, где важна каждая недоговорённость.','/posters/11.svg','#76513a') ON CONFLICT DO NOTHING;
INSERT INTO movie_genres(movie_id,genre_id) VALUES (11,5),(11,3) ON CONFLICT DO NOTHING;
INSERT INTO quotes(id,movie_id,text) VALUES(11,11,'Истина — забавная вещь.') ON CONFLICT DO NOTHING;
INSERT INTO movies(id,title,original_title,year,director,duration,description,poster,accent) VALUES(12,'Вечное сияние чистого разума','Eternal Sunshine of the Spotless Mind',2004,'Мишель Гондри',108,'После расставания герой решает стереть воспоминания о любимой. Но внутри исчезающей памяти обнаруживается то, с чем он всё ещё не готов попрощаться.','/posters/12.svg','#426d83') ON CONFLICT DO NOTHING;
INSERT INTO movie_genres(movie_id,genre_id) VALUES (12,6),(12,1) ON CONFLICT DO NOTHING;
INSERT INTO quotes(id,movie_id,text) VALUES(12,12,'Встреть меня в Монтоке.') ON CONFLICT DO NOTHING;
